services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.local
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      DB_HOST: db
      NODE_ENV: development
      IDO_SELL_API_KEY: ${IDO_SELL_API_KEY}
      IDO_SELL_URL: ${IDO_SELL_URL}
  db:
    image: postgres:18
    container_name: cosibella_postgres_db
    environment:
      POSTGRES_USER: ${DB_ROOT_USER}
      POSTGRES_PASSWORD: ${DB_ROOT_PASSWORD}

      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/cosibella/data
      - ./scripts/database:/docker-entrypoint-initdb.d
      - ./src/migrations:/migrations

volumes:
  pgdata:
